language: python
matrix:
    allow_failures:
        - os: osx
    include:
        - os: osx
          language: generic
        - os: linux
          sudo: required
          python: 3.4
        - os: linux
          sudo: required
          python: 2.7
before_install:
  - ./.travis/before_install.sh
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install flake8 pytest
  - pip install .
# command to run tests + check syntax style
script:
  - python setup.py develop
  - flake8 examples/ ot/ test/
  - python -m py.test -v test/
  # - py.test ot test
